### ISSUE TITLE
QUESTION: What are tractor beams?

### ISSUE THREAD

**Issue by HUg0005** [smcameron/space-nerds-in-space#105]
I cannot seem to find any documentation that describes the tractor button in sci. What is it and when would you use it?

**Comment by smcameron** [comment]
It doesn't work very well, but the best use case is probably when you're chasing down cargo containers ejected from destroyed ships.  Get close to the container, select it from science, then hit the tractor beam button.  The you can switch to weapons and see the beam pulling in the cargo container.  It's kind of sort of Newtonian, in that it puts a force on the tractor beam towards your ship, so you can end up with the container kind of swinging around and orbiting your ship, rather than being drawn smoothly towards it -- so that's why I say it doesn't work very well.  That's more or less why I haven't written about it because in the back of my mind I have the idea that it should work better and have some better use cases -- exactly how or what those might be, I'm not sure.

**Comment by smcameron** [comment]
The TRAINING-MISSION-2.LUA script actually expects you to tow a derelict ship with the tractor beam.

https://github.com/smcameron/space-nerds-in-space/blob/master/share/snis/luascripts/TRAINING-MISSION-2.LUA

I haven't run that mission in a long time.

**Comment by HUg0005** [comment]
Thanks.

**Comment by smcameron** [comment]
Made a mention of the tractor beam on the help screen for science (not much, but at least it is mentioned.)

commit 7b0d9013b572deb8080507c0eaccadf0e8abba5d
