### ISSUE TITLE
snis binaries are rebuilt during install

### ISSUE THREAD

**Issue by the-maldridge** [smcameron/space-nerds-in-space#114]
I have yet to determine exactly why, but build_info.h is regenerated during install and this causes all of the binaries to be rebuilt as well.  I don't think this is intentional and I really think it shouldn't happen at all.

**Comment by smcameron** [comment]
It's because build_info.h depends on .FORCE, as described here:
https://www.gnu.org/software/make/manual/html_node/Force-Targets.html

build_info.h used to contain a timestamp, but that was removed by:
5e9139c4cf35fe69f2c5823a71c680124fcb98b8

Probably the .FORCE business can be removed since it's probably only there to force regeneration of the build timestamp that no longer exists.

**Comment by the-maldridge** [comment]
TIL.  I'll submit another PR for that.

**Comment by smcameron** [comment]
Committed as a patch.
