### ISSUE TITLE
is glew required?

### ISSUE THREAD

**Issue by tuxutku** [smcameron/space-nerds-in-space#121]
trying to build for clearlinux and clearlinux does not provide glew.h, is it there any option to pass glew?
output of make 0=1 :
[log.txt](https://github.com/smcameron/space-nerds-in-space/files/1488946/log.txt)

uname -a :
Linux clr-449e9b2a44f8458bb4885604dc172a1c 4.13.12-430.native #2 SMP Thu Nov 9 14:13:59 UTC 2017 x86_64 GNU/Linux

**Comment by smcameron** [comment]
glew is required for snis_client, but shouldn't be needed for snis_server or snis_multiverse.

I notice that clearlinux appears to be a distro that is focused on cloud/containers. I can see why they might omit glew, and other opengl type things, since opengl apps aren't the sort of thing that is usually run in a cloud environment.

If you intend to run only snis_server and snis_multiverse on clearlinux then I expect that snis_server should build ok with just:

make snis_server snis_multiverse

without requiring glew or any opengl stuff or audio stuff. Requirements for snis_server should be pretty minimal.

scameron@sirius ~/github/space-nerds-in-space $ ldd snis_server
	linux-vdso.so.1 =>  (0x00007ffc47bca000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fbaa5cb8000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbaa5ab4000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbaa57ae000)
	liblua5.2.so.0 => /usr/lib/x86_64-linux-gnu/liblua5.2.so.0 (0x00007fbaa557d000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007fbaa5344000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbaa5126000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbaa4d61000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fbaa5ec0000)

Nothing there that isn't pretty standard stuff. snis_multiverse is similar.

I don't really recommend running it in the cloud though because:

1)  the game isn't really designed with that in mind (it's more a LAN game) although it might work if you have a solid connection (I haven't tried running it remotely like that in years, I wouldn't be very surprised if it does not work very well when run that way.)
2) There's no proper security for the accounts (because it's meant to be a pretty transient LAN game.)

If you mean to run the client, you're going to need glew.

**Comment by tuxutku** [comment]
sorry for late repply, i have glew and gl installed and running but my disturbituon doesn't provide the header files of them as i get it today, now  i am trying to get those headers if there is a way to, i am new to linux for a bit so i don't realy now if i recompile the glew, my system will be stable

if i have gramer issues sorry for that.

**Comment by smcameron** [comment]
Perhaps you need to install  glew-dev-1.13.0-3.x86_64.rpm

https://distrowatch.com/dwres.php?resource=compare-packages&firstlist=clear&secondlist=debian&firstversions=0&secondversions=0&showall=yes#allpackages

**Comment by tuxutku** [comment]
downloaded glew source code and copied GL folder to /usr/local/include and it worked, closing the issue now
