### ISSUE TITLE
Mouse capture on the weapons screen

### ISSUE THREAD

**Issue by haydenhughes** [smcameron/space-nerds-in-space#125]
Just a suggestion but it would be much easier it aim if the mouse was being captured on the weapons screen and allow you to properly rotate using the mouse without hitting the borders of the monitor.

**Comment by smcameron** [comment]
Thanks for the feedback. I'm not entirely happy with the way the mouse works with weapons. I'm not sure what you mean by capture -- if you mean prevent the mouse from leaving the window, that sounds... inconvenient, I seem to recall vmware used to be able to do that, and I always found it rather horrible, but using the mouse input only while in the window, and ignoring it while out of the window might be reasonable. ... hmm, just tried it and that is what I already do.  That is, if the window is not full screen, you do not have to move to the edge of the monitor, only to the edge of the window. So I don't think I quite understand what you are requesting.

Part of my reasoning for having it work the way it does is so that you could, for example, always aim straight ahead by moving your mouse to the bottom center of the window -- if I do some relative scheme where the aiming is not directly mapped in a fixed way to mouse position within the window, each time you want to aim a particular direction (e.g. straight ahead), you'll have to figure out what that is at the moment instead of just knowing that it's bottom center of the window.

So, I'm not sure I understand what behavior you are requesting. I am open to improving it, and I'm also open to having several different ways it could work, selectable by the user (in the vein of inverted/non-inverted vertical controls on navigation), as surely different people will likely have different preferences about how it should work.

So, what do you mean by "capture the mouse?" And what would be the procedure with your proposed method for say, aiming straight ahead?

**Comment by HUg0005** [comment]
Sorry I should have explained myself better. By capture the mouse I meant similar action to a first person shooter (e.g Overwatch, Counter Strike, etc.) where rotating the player using the mouse is not limited to the width of the screen allowing you to spin 'indefinitely'. Although now that you have explained it I can see why it works like the way it is, although I still think it's cumbersome.

**Comment by smcameron** [comment]
I haven't played those games. Can you explain how you think it should work in detail?

**Comment by HUg0005** [comment]
So on screen the cursor is hidden as it is not required. When I move the mouse left the aim of the weapons screen moves left respectively in relation to how much I move the mouse. There is no limit to how much left I can move the mouse, the turret would just keep spinning until I ran out of space on my mouse mat. Similarly right, up and down movements would have the similar effects but up and down movements can have restrictions to stop the turret from shooting the ship or doing strange spinning actions.

Now I how I think this generally works in games are the mouse is centered every frame. When the mouse moves the delta is calculated and the mouse is re-centered at the end of the frame. The turret would then move depending on the calculated mouse movement. 

When it comes to the mouse leaving the window, alt-tab on every OS and window manager I have tried will disengage the mouse from the window when switching windows. Also when you press escape you could have the cursor reappear and disable the centering. The same would also apply when switching screens. 

I hope this clears things up.

**Comment by smcameron** [comment]
Yes, that clears things up. Thanks. I'll see what I can do.

**Comment by smcameron** [comment]
Ok, I took a stab at it with commit 1ad9ddfef01b7bf881aed77cbab3b6ac660d25e5

I think it behaves as you described, but probably needs some tuning to be very usable.

Press CTRL-m on the weapons screen to toggle between the old and new modes.

See what you think.

**Comment by HUg0005** [comment]
Looks good. Movement needs to be smoothed out a bit and if you can stop the bit of drift to make it more accurate then that would be perfect. Thanks and keep up the awesome work. :smile:

**Comment by smcameron** [comment]
This got broken by b384b075ab5142d5e6f46fdb2356c2f9882e043c which introduced key_sci_mining_bot, which is "m", same as key_mouse_mode, and overrode key_mouse_mode.

**Comment by smcameron** [comment]
Fixed mouse mode and mining bot button conflict (or at least hacked around it) with 71ff56c92ba2beb50d5072ae00a0adc43a4e2628
