### ISSUE TITLE
Easy way to Update to the latest SNIS?; Version Control

### ISSUE THREAD

**Issue by angrystatic** [smcameron/space-nerds-in-space#170]
What is the easiest way to update an installation of SNIS to the lastest version?

What is the easiest way to roll back if that's required for some reason?

I'm guessing this has been answered somewhere else but I'm having trouble finding it.

I'm also assuming that there isn't a SNIS package repo. Again, very Newb questions. SNIS is currently the main reason I'm tinkering with Linux. I need strong motivators... :)

**Comment by smcameron** [comment]
Hi,

You're correct that there's no package repo.

Best way to update is as follows:

```
cd space-nerds-in-space
make mostly-clean
git pull
make
make update-assets
```

One thing that is possible to happen (but rarely does) is the stuff that snis_multiverse creates in space-nerds-in-space/snisdb/ gets out of whack if it is different enough between versions (it doesn't change much, and most changes are compatible between versions anyway). What is in there is the state of all the player ships preserved between games.  At the moment this is not really very valuable, so it is pretty safe to just blow away snisdb/ (you will lose any existing player ships, but you can just make them again, when you start the first snis_client by checking the CREATE SHIP box on the network setup screen.  Hope that makes sense. If not, maybe this will help: https://smcameron.github.io/space-nerds-in-space/#bridgeverification )

If you ever happen to see that the big spinning ship on the network setup screen appears excessively spherical, it probably means you need to do the above procedure (make mostly-clean; git pull; make; make update-assets)

As far as rolling back, I try pretty hard (but not absolutely 100% successfully) to make sure every commit should be more or less OK, so that git bisect can work.  That also means you can do "git log" and find any commit you want to roll back to (maybe by date, if you don't have a clear idea what you want to roll back to), write down the SHA then:

For example:

```
scameron@wombat ~/github/space-nerds-in-space $ git log
commit 403f0d9791e9a157e080da1c28de34d7bae9fb2e
Author: Stephen M. Cameron <stephenmcameron@gmail.com>
Date:   Fri Oct 26 13:16:36 2018 -0400

    Update credits

commit 4fe40914dc312b36649dcddc3aae4f0005a5d560
Author: Stephen M. Cameron <stephenmcameron@gmail.com>
Date:   Thu Oct 25 14:00:27 2018 -0400

    Update damage script

commit 30e111346580f4a447ed47d679e4573678ff4cce
Author: Stephen M. Cameron <stephenmcameron@gmail.com>
Date:   Sat Oct 20 21:42:54 2018 -0400
[ ... lots more omitted ... ]
```

The big crazy string after "commit" is the SHA.

```
SHA=30e111346580f4a447ed47d679e4573678ff4cce 
git branch ${SHA} my_rollback_branch
git checkout my_rollback_branch
make mostly-clean
make
make update-assets
```

You can do "make clean" instead of "make mostly-clean" if you want to, but it will cause assets to get downloaded a 2nd time unnecessarily.

The farther back in time you go, the less likely rolling back is to work. (because compilers get new warning messages, and for awhile in the early days I had -Werror turned on, and for a variety of other miniscule reasons). That being said, I have recently (just this week in fact) checked out a variety of commits spanning the entire six years of development of SNIS and made them all run (some early ones required some fixing to make them run again.)

Note that a good portion of the assets aren't in git, so there's no good way of rolling back those, but I think none of the assets that are not in git are *required* by anything, so I think that shouldn't be a problem.

Hope that helps, and feel free to ask questions if you have trouble with it.

I should probably put this info on the web page.

-- steve

**Comment by smcameron** [comment]
BTW, the client and server protocol version numbers are visible on the lobby screen:
![snis-lobby](https://user-images.githubusercontent.com/23912/47625023-8b61ff00-daf8-11e8-8fff-d67533e4e366.jpg)

**Comment by smcameron** [comment]
Added some build instructions to the web page. 81ee35d5c411334d5e70e3f3ad7d7ba1c6a48b7d
