### ISSUE TITLE
shipname is not available in get_ship_attribute

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#199]
https://github.com/smcameron/space-nerds-in-space/blob/master/lua-api.txt advertise a **shipname** attribute, but it does not work, it seems the correct one is **sdata.name** instead.

**Comment by smcameron** [comment]
Yeah, that section is out of date.

It's the output of print_ship_attributes.

scameron@sirius ~/github/space-nerds-in-space $ make print_ship_attributes
cc -o print_ship_attributes print_ship_attributes.c key_value_parser.o
scameron@sirius ~/github/space-nerds-in-space $ ./print_ship_attributes | grep shipname
scameron@sirius ~/github/space-nerds-in-space $ 

There is a get_object_name(id) that should get the name of a ship.

**Comment by smcameron** [comment]
get_object_name(id) does handle a special case for starbases... (starbases have a special tsd.starbase.name field ... I forget exactly why.  Might be so you can know starbases even if they haven't been scanned, might be purely historical garbage due to starbases being one of the first object types added into the game.)

Anyway, committed 016f3125ee2796bf40d249c375b064c86d20d4d9

**Comment by smcameron** [comment]
Got rid of the special case for starbase names: 593a3c099d8c6a1d9f3b4694d753964f081cc133
