### ISSUE TITLE
Duplicate default server?

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#247]
When using snis_launcher and then option 1, 2, 3 then 4, I see two servers with default system, but one is quoted.

I’m pretty sure this is new.
![Screenshot_20200220_152334](https://user-images.githubusercontent.com/106382/74952334-705b8280-5400-11ea-8728-d670484922fa.png)

Also, when starting a second snis client on the same computer, I do not have the menu on top left to select the detected lobby, it only works for the first client launched, not sure why.

**Comment by smcameron** [comment]
Hmm, not sure where those quotes are coming from.  Definitely a bug.

> I do not have the menu on top left to select the detected lobby

Do these computers you're using have access to the internet, or are they on a local network without internet access?  Also, are they multi-homed (have more than one network interface)?

If you are running on a private network without internet access, or on an internal network rather than then the internet-facing network, then you might need to do something like this:

```
        export SSGL_PRIMARY_IP_ADDR_PROBE=192.168.1.1
	./snis_launcher
```

(substitute your IP address for 192.168.1.1 of course).

If that helps, then what's happening is the game is basically asking the kernel, "hey, suppose I wanted to send a packet to 8.8.8.8 (google's DNS), which network interface would that packet go out?", and the kernel tells it, and so that's how it figures out which interface is "internet facing".  It is then broadcasting the packets that tell where the lobby server is on that internet facing interface.  This is on the (somewhat questionable) presumption that in most cases the interface that can reach the internet is the same interface that can reach other SNIS clients.  The SSGL_PRIMARY_IP_ADDR_PROBE variable lets you override this behavior to get it to broadcast via an internal facing interface instead.  Hope that all makes sense.

I'm not quite sure what the ideal behavior is (maybe broadcasting on all interfaces unless you tell it otherwise), but there are other complications having I think to do with getpeeraddr()... but I can't quite remember what all the other complications are that led me to do it this way.

**Comment by smcameron** [comment]
Ok, I think I found the extra quotes.

* c2798aba93faacd434845c308ddd60ad1915daa2  Fix problem with extra quotes on solarsystem name

**Comment by smcameron** [comment]
The extra quotes were introduced by this commit on Feb 1, 2020:
 Fix some issues found by shellcheck  6cbc8846c8c0518a7019e9a1e4a91988ea81a4a1

**Comment by MCMic** [comment]
This is all on one computer facing the internet through local network. The first snis client detect the lobby at 192.168.1.19 (which is my internal ip on local network), the second snis client does not auto detect anything. It bugs me that two client on the same computer do not behave the same.

**Comment by smcameron** [comment]
Huh.  That's weird.  I will have to experiment and see if I can duplicate it.

**Comment by MCMic** [comment]
I can confirm first problem is fixed.

For the autodetect, even If I do not connect the first client, I just launch two of them in one window I have the menu and not the other one. (It seems consistently the first launched which get the menu)

**Comment by smcameron** [comment]
Ok I think I understand the problem, have duplicated it and have a fix.  The problem is that by default, two applications on the same host cannot bind to INADDR_ANY at the same time.  Need to use socket option SO_REUSEADDR on the receiving side to allow this.  Normally I didn't hit this (or didn't notice it) because I either run everything on the same host (in which case the default localhost will work so I didn't notice the menu was missing on some clients) or run only single clients on hosts other than that running snis_server (so the menu would work in those cases).

* 375da51777186966016dcebe5be21b371433782c Allow multiple snis_clients on same host to receive ssgl broadcasts

**Comment by MCMic** [comment]
Yep, fixed! Thanks.
