### ISSUE TITLE
Support several presets on engineering screen

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#252]
I would like to allow the engineer to save presets other than the default 1/2, allowing to save presets for warping, fast cruise, fight mode and so on as he pleases.

My current idea on this is to move the damage control button to the bottom right (the idea is to have it on the same position as the engineering button on damage control screen, allowing to go back and forth without moving the cursor), to leave some place to something like 8 or 6 presets buttons.

Open questions:

- Should the default 1/2 presets be editable like the other or have a special status? Maybe only the first one which could be given a label like "off" or 0? (I’m leaning toward giving no special status, leaving the engineer responsible for his setup)
- How should saving works? Either as soon as I’m on a preset and I change something it’s saved, making them behave like tabs where one is always active, or there is a save button which saves the preset? (and still we’ll need a preset to be considered active to know which one we are saving to)

@smcameron I’m ok to work on the implementation for this if you like the idea.

**Comment by smcameron** [comment]
Yeah, this is a good idea, and something I've thought about a little bit (but only enough to think "I should do that.")

I agree 1 and 2 should not have special status and it should be up to the user what the presets do.

I think the presets should probably not autosave when you make a change.  Maybe make saving work like old school car radio buttons?  Click on the preset, it activates the preset on mouse release. Lean on the preset button for a full second then release, and it saves current values? Tool tip can explain that behavior. (well, this might not behave well with my physical consoles project... or be somewhat hard to implement.)

Should presets be per-bridge, or per-station?  That is, if you have two instances of the engineering station, should they be permitted to have different presets?  And should presets persist across sessions (be saved with the ship data?).

Per station presets that do not persist across sessions are easiest, but per-bridge presets that persist are probably better and more consistent with how the rest of the game works, and that is what I would do (well, because that's a bit hard, it is probably the reason I haven't done this already.)

**Comment by MCMic** [comment]
I think I will try having always the last pressed preset button active and a save button.

Regarding saving, I do not have a strong opinion, as far as I know there is not much use having several computer with the same station ? (As it’s not possible like for 2 science stations to look at 2 different objects)
The only usecase I see is several stations having engineering as secondary if you do not have a dedicated engineering station.

Persisting across sessions does sound good though. Would make it feel a little more like going in the same ship as last session. I will try this and see how hard it gets.

**Comment by smcameron** [comment]
The primary use case for several computers with the same station is to allow any station to be viewed on the main screen.  So in general, I have tried to have as much of the ship's state as possible be on the server, and as little as possible on the client.  That way, if any two computers are on the same station, they show the same thing.

**Comment by MCMic** [comment]
I never noticed before that the shield slider is also modified by the presets.
I’m not sure this slider makes sense, since we should always have shields to the maximum, except for docking where we disable them, maybe it should be a checkbox? (there is already a slider for shield powering)

**Comment by MCMic** [comment]
I’m hitting a wall on a build failure.

I had a crash of multiverse server with «bridge packet size is wrong (actual: 346, nominal: 238)»
As I added 6 presets * 18 sliders, this 108 difference is expected.
So I updated UPDATE_BRIDGE_PACKET_SIZE to be 346, and I hit:
```
  COMPILE snis_multiverse.c
Dans le fichier inclus depuis snis_multiverse.c:53:
snis_multiverse.c: Dans la fonction « update_bridge »
build_bug_on.h:7:25: erreur: la taille du tableau sans nom est négative
    7 | do { (void) sizeof(char [1 - 2*!(cond)]); } while(0)
      |                         ^
snis_multiverse.c:539:2: note: dans l'expansion de la macro « BUILD_ASSERT »
  539 |  BUILD_ASSERT(sizeof(buffer) > bytes_to_read);
      |  ^~~~~~~~~~~~
```
(pardon my french, as they say…)

So I tried changing `unsigned char buffer[250];` to `unsigned char buffer[350];` and it does not fix it, I also tried 358 and 10000, it does not avoid the crash.

@smcameron What did I miss?

**Comment by smcameron** [comment]
Not sure.  I tried the following just now and it builds OK (won't run right of course):

```
diff --git a/snis_bridge_update_packet.h b/snis_bridge_update_packet.h
index 3360345..78df609 100644
--- a/snis_bridge_update_packet.h
+++ b/snis_bridge_update_packet.h
@@ -29,7 +29,7 @@
 #include "snis_marshal.h"
 #include "snis_multiverse.h"
 
-#define UPDATE_BRIDGE_PACKET_SIZE 238
+#define UPDATE_BRIDGE_PACKET_SIZE 346 
 
 struct packed_buffer *build_bridge_update_packet(struct snis_entity *o, unsigned char *pwdhash);
 void unpack_bridge_update_packet(struct snis_entity *o, struct packed_buffer *pb);
diff --git a/snis_multiverse.c b/snis_multiverse.c
index d8fddcb..1187e2e 100644
--- a/snis_multiverse.c
+++ b/snis_multiverse.c
@@ -521,7 +521,7 @@ static int update_bridge(struct starsystem_info *ss)
 {
        unsigned char pwdhash[PWDHASHLEN];
        int i, rc;
-       unsigned char buffer[250];
+       unsigned char buffer[358];
        struct packed_buffer pb;
        struct snis_entity *o;
 
diff --git a/snis_server.c b/snis_server.c
index dcb23c3..c63c750 100644
--- a/snis_server.c
+++ b/snis_server.c
@@ -28520,7 +28520,7 @@ static int process_update_bridge(struct multiverse_server_info *msi)
 {
        unsigned char pwdhash[PWDHASHLEN];
        int i, rc;
-       unsigned char buffer[250];
+       unsigned char buffer[358];
        struct packed_buffer pb;
        struct snis_entity *o;
        double x, y, z;
```

Send me a diff of the changes you're made and I can take a look.

**Comment by MCMic** [comment]
@smcameron Ok, I missed that there is the same code in snis_server and snis_multiverse, I thought I was hitting the same failure while it was a different one.

**Comment by smcameron** [comment]
I find it is always a pain when I have to change that area of the code.  Those BUILD_ASSERTs are part of my attempts to make it less painful, but it is still always painful because there are a lot of moving parts that interact around there.

**Comment by smcameron** [comment]
> since we should always have shields to the maximum

Hmm, it is a little strange, but only because the shield control happens to be on the same screen as all the engineering power level controls, so the engineer can set the shield control to maximum, and then control the level of the shields with the shield power control (or vice versa).  Both controls are essentially modelling resistors in a circuit, and they are in series with each other.  Setting max power is, iirc, setting the modelled resistor to 0 ohms (but there is another fixed resistor in series so you don't ever get infinite current.)

It's because of the way the power model is done... see power-model.h 

6 presets seems like a lot.

**Comment by smcameron** [comment]
I noticed the "heal player ship" menu item on the demon screen, which ultimately calls init_player_ship() clears the presets.  I expect docking at a starbase will also clear the presets.

**Comment by smcameron** [comment]
*  Allow engineering presets to persist across init_player() 4c41e2272f610c1640215b2bf20f9e5950390e53
*  Fix memory leak in power model code 76613b40a47db3276e76d70a417200e1589b72dd

**Comment by smcameron** [comment]
Hmm, it occurs to me that we are storing the presets in the power_model_data, and we are transmitting this data from the server to the client in snis_bridge_update_packet because we do this:

```
        packed_buffer_extract(pb, "r", &power_data, (uint16_t) sizeof(struct power_model_data));
        packed_buffer_extract(pb, "r", &coolant_data, (int) sizeof(struct power_model_data));
```

So, it was kind of neat to be able to transfer the data to the client without changing that particular bit of code...

However, it now occurs to me that the client does not actually *need* this data, or do anything with it.  It only tells snis_server which preset to select, or which preset to save current settings in.

What's more, these 108 (or whatever) new bytes of preset data are contained within struct ship_data which is in a union that is in *every* snis_entity, even though only player ships ever use it.  So, multiply this by a few thousand entities, and we're talking about 100s of kilobytes of memory being wasted.  I don't know why this didn't occur to me earlier.

So, I think I should look into moving the engineering preset data into bridgelist[] within snis_server.

**Comment by smcameron** [comment]
*  Revert preserving engineering presets across init_player()  ab053b077586422dd9eb212d9effbdd7b07b2c62
*  Move engineering preset data from snis_entity to bridgelist b975827b98ceaaffd54a78189d4d524abe1a32f1

**Comment by smcameron** [comment]
*  Revert preserving engineering presets across init_player()  ab053b077586422dd9eb212d9effbdd7b07b2c62
*  Move engineering preset data from snis_entity to bridgelist b975827b98ceaaffd54a78189d4d524abe1a32f1

**Comment by smcameron** [comment]
*  Set disabled color for engineering preset save button e195ed132d38d5441abca34f0779ac254d7e5215

**Comment by MCMic** [comment]
@smcameron Why did you remove the BUILD_ASSERT? Your code still depends on the constant being 6.

My commit MCMic@c56bd91 for default presets will need to be adapted. (I may do it, but can’t right now)

**Comment by smcameron** [comment]
Good catch, thanks.  I thought that I was going to move it to a different place early on, then forgot to put it back when that ended up not being the case.  Sorry about clashing with your default presets patch.

*  Put build assert for engineering preset back  8686624be43c186fe29880f69e0017710d6bc63f

**Comment by smcameron** [comment]
I think we're done with the presets now, right?  I'm going to close this issue.  If you think there's more to be done, feel free to re-open it or start a new issue.

**Comment by MCMic** [comment]
@smcameron It seems when saving with long button press there is no feedback at all?

**Comment by smcameron** [comment]
There is feedback when you release the button, in that when you release the button, the new preset is then selected.  There could and probably should be a different sound played when the long press is activated (when the button is released).

I don't see a practical way to give feed back *during* the long press (prior to releasing the button) because the button is only "aware" of the press and release events, not any "hold" kind of state.  There is some tracking of the "hold" state for the mouse (used on science to rotate the 3D long range scanner view), but the button has no visibility into this, and a reasonable API for the buttons to have this info is not occurring to me, though I haven't thought about it super hard.  It would be nice if the buttons behaved like a car radio in that if you press and hold them, after a second or two they beep even before you release the button to indicate the preset has been saved.

**Comment by MCMic** [comment]
When releasing the button, it shortly moves with an offset, as if pressed.
I would expect the offset to appear when I press and disappear when I release.

> after a second or two they beep even before you release the button to indicate the preset has been saved.

Yeah I was expecting this, it’s sad that it’s technically complicated.
