### ISSUE TITLE
Default star system appears twice

### ISSUE THREAD

**Issue by MCMic** [smcameron/space-nerds-in-space#295]
When using snis_launcher options 1, 2 and 3 to start server and lobby, I end up with two instances of the default starsystem in the lobby when I connect with snis client, one labeled `default` and one `"default"`.

The other star system names are unquoted so I guess the buggy one is the quoted one.

**Comment by smcameron** [comment]
Interesting.

When I try it on my system, I end up with only one entry, "default", with the quotes.

snis_launcher prints out the processes that are running.  Does it print out two instances of snis_server?

**Comment by MCMic** [comment]
Yes, it does list two instances:
```
The following SNIS processes are running:
        LOBBY SERVER -- mcmic       2817  0.0  0.0 617508  2320 ?        Ssl  11:05   0:00 ./bin/ssgl_server
   MULTIVERSE SERVER -- mcmic       2856  0.0  0.0 368568  3348 pts/3    Sl+  11:05   0:00 ./bin/snis_multiverse -a -l localhost -n nickname -L narnia -e default
         SNIS SERVER -- mcmic       2889  0.7  0.1 543088 10272 pts/3    Sl+  11:05   0:01 ./bin/snis_server -l localhost -L DEFAULT -m narnia -s default
         SNIS SERVER -- mcmic       2891  1.8  0.1 329692  9592 pts/3    Sl+  11:05   0:04 ./bin/snis_server -l localhost -L KARADO -m narnia -s karado
         SNIS SERVER -- mcmic       2893  2.0  0.1 329692  9652 pts/3    Sl+  11:05   0:05 ./bin/snis_server -l localhost -L POLARIS -m narnia -s polaris
         SNIS SERVER -- mcmic       2895  2.2  0.1 329692  9588 pts/3    Sl+  11:05   0:05 ./bin/snis_server -l localhost -L ZOLON -m narnia -s zolon
         SNIS SERVER -- mcmic       2916  1.7  0.1 329692  9860 pts/3    Sl+  11:05   0:04 ./bin/snis_server -l localhost -L "DEFAULT" -m narnia -s default
         SNIS CLIENT -- mcmic       4401 85.0  0.9 1394200 79672 pts/3   Rl+  11:09   0:00 ./bin/snis_client --lobbyhost localhost --fullscreen
```

**Comment by smcameron** [comment]
Ok, I think I duplicated the problem by the following sequence:

```
./snis_server
1 (start ssgl)
3 (start snis_server)
2 (start snis multiverse, with autowrangling on)
```

So I think the problem is that snis_launcher starts snis_server with the extra quotes, but I wasn't seeing the problem because I always started things in this order "1, 2, 3", not "1, 3, 2".

Although I don't have a good explanation for why "1, 2, 3" doesn't exhibit the same problem, but in any case, removing the extra quotes from snis_launcher should fix it I think, because if DEFAULT snis_server is started twice, the lock file system should prevent two snis_server instances with the same name from being started, and now both snis_launcher and snis_multiverse should both use DEFAULT rather than one using DEFAULT and one using "DEFAULT".

Should be fixed by 465870caa1addd83fee41a86ad746bc7bee0e69d

**Comment by smcameron** [comment]
One more commit because I accidentally put two uppercase operations in a row (not necessary for the fix): 911f1c9322bd2ffd1c5d7bd0bdd49147d9bde0d4

**Comment by MCMic** [comment]
I did have the problem using 1 2 3 in that order with default options. Maybe I did them fast and 3 started before 2 finished through.

**Comment by MCMic** [comment]
It does seem fixed by the commit.
