### ISSUE TITLE
inconsistencies in help function on comms screen

### ISSUE THREAD

**Issue by heaventwig** [smcameron/space-nerds-in-space#339]
On the communications screen, the help info obtained by hitting f1 is quite different from the info obtained by hitting the help button or typing /help into the input box.

This could maybe be intentional, but it might also be amenable to correction by setting up (if it's not already set up) a set of help files, one per screen, that can then be localized for other languages by anyone who cares to take on that particular project. If those are basically raw text, so much the better. Might be important to include a pointer to them in the comments on whatever code implements the screen and its i/o elements, of course.

**Comment by smcameron** [comment]
>  localized for other languages

Not happening because locales are [fatally broken](https://github.com/smcameron/space-nerds-in-space/issues/41) -- by which I mean I have code that parses ASCII STL files (and wavefront OBJ files) that contain ASCII representations of floats using sscanf, and sscanf's behavior changes depending on locale in a way that breaks parsing of floats (e.g. French locale wants commas, not periods for decimal point), so I "fixed" it with [a sledgehammer that forces the locale to "C" as the gods intended](https://github.com/smcameron/space-nerds-in-space/blob/master/c-is-the-locale.c).

That being said, the help can possibly be made consistent in the "C" locale.

**Comment by heaventwig** [comment]
I read the comment thread you linked, skimmed through your epic back-and-forth troubleshooting it, and finally lolled when I read the comments on that localization code. I concur, and had no idea anyone would implement it so poorly: localization of data files is ludicrous, and not in the good way. Oh well.

So nevermind the localization concept.

I still think it might be useful to have the help screen text either fully separated from the code or, Knuth-like, fully embedded in it such that the documentation presented in the game about how to play the game is generated by the code that runs the game from an alternative parsing it does of itself at runtime (or maybe just when compiling, idk). Because if it's not Knuth-level embedded in the code, there will (nearly) always be a help-docs maintenance step on any codebase changes that update UI/UX.

**Comment by smcameron** [comment]
> alternative parsing it does of itself

Hell no.

> always be a help-docs maintenance step

That is unavoidable.  Putting the help into its own file doesn't make this much better or worse, it's about the same.  Without a significant advantage one way or the other, I see no reason to change the way it currently works (which it's just an array of strings called help_text[] in snis_client.c).

**Comment by smcameron** [comment]
Alright, looking again...  I now remember the comms /help command is a special case, because it's blasting the help text through the comms system when means it gets transformed into commands transmitted from snis_server to snis_client, line by line.

Unifying the comms help text in snis_server with the help text in snis_client.c (without duplicating it, as it is now) will necessarily complicate the code either in the server, or in the client (though not too much).

**Comment by smcameron** [comment]
* c9bd8ded3dd299b035d7148578d2b2036871e1bd Factor out help text
 * dc1b7c0cc558c607973b07ce2da6489c53b66a9c Unify comms client/server help text
