### ISSUE TITLE
Windows build throws errors

### ISSUE THREAD

**Issue by SmallJoker** [smcameron/space-nerds-in-space#53]
I doupt this game was thought for Windows but I wonder if someone is going to make it compatible.
Please tell me if there's a need for an error log, it's huge.

**Comment by smcameron** [comment]
Hi,

Thanks for taking a look at Space Nerds In Space.

Yeah, I'm afraid the game is not made for windows.  The only target so far has been Linux.  I also know that it has been made to work on Mac OSX by at least one person, using Mac versions of the various libraries needed (gtk, gtkglext, portaudio, etc.)

That being said, I am aware of an effort (not by me) to create a set of patches to get SNIS to use SDL instead of gtk, which, should those patches materialize, would undoubtedly make a windows port a lot easier and more likely (though still not an easy slam dunk.)  I don't know whether this effort to switch to SDL will be completed, and those patches might never materialize, so don't hold your breath.  I don't own any windows machines, so if a windows port does materialize, it will have to be done by someone other than me.

-- steve

**Comment by SmallJoker** [comment]
I am not a cood C(++) coder, so it would be great if there was someone with enough time to switch SNIS to SDL. There are some space nerfs out there who don't even know about this game and Windows support is definitely a forward jump.

**Comment by JeffM2501** [comment]
Steve, if you received pull requests for SDL support, would you be willing to merge those in or would you want that maintained as a fork?

**Comment by smcameron** [comment]
Patches are preferable to pull request. The sdl code i am aware of is
actually quite far along.  I think the most difficult part is/was the
keyboard handling.

**Comment by JeffM2501** [comment]
If it doesn't get finished, let me know, it should not be too hard of a thing. Keyboard handling in SDL 2 is pretty easy.

**Comment by Toumal** [comment]
Who is working on the sdl port? Perhaps we could split up efforts? ^^

**Comment by smcameron** [comment]
FWIW, the aforementioned port to SDL seems to have stalled, so if someone else would like to take a crack at it, feel free.  If you can do it without breaking the existing stuff, that's better, but I realize that is a tall order.  Also, a series of a large number of smaller patches (where each patch in the series builds and runs) is preferable to a series of a small number of large patches.  Smaller patches is better, but the patches need to work all along the way to enable git bisection.  (Stacked git can be very helpful in constructing such a patchset.) https://gna.org/projects/stgit

**Comment by smcameron** [comment]
FWIW, SNIS has been built successfully on Windows 10 using the linux subsystem (i.e. using Windows 10 abiltity to run linux binaries, and gcc was used to compile.)  There were performance issues though, since ti appeared to be using a software implementation of opengl.

I'm going to close this issue now, since running the game on windows was never really a design goal, and there's not really any work going on to make it portable to windows.

If you want to run it on windows, run linux in a VM on your windows machines and run it in the VM, or boot linux on your machines using USB flash drives.

**Comment by SmallJoker** [comment]
Actually I thought this issue was closed long ago due to lack of interest. It's been a while and I'm happy to see it running on Windows as well, although I've switched to Linux in the meantime.
Thanks a lot for your effort and keep up the good work :+1:

**Comment by edthedev** [comment]
Quick update on this, since I had the same challenge. I have created a fork that adds a Vagrantfile, for anyone who wants a recipe to quickly set up the game inside a virtual machine.
